OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-WUVjTMqzcNGj4D4d6dC5Ce1520E841C59a787011D9CeAb8c"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"
  original_language: "英文"
  target_language: "中文"